export const quotes = [
  "Small steps every day lead to big changes.",
  "Consistency beats motivation.",
  "You don't have to be perfect, just consistent.",
  "Discipline is choosing what you want most.",
  "Habits shape your future.",
  "Progress, not perfection.",
  "Your daily habits define your success.",
  "Little by little, a little becomes a lot.",
  "The journey of a thousand miles begins with a single step.",
  "Success is the sum of small efforts repeated day in and day out.",
  "You are what you repeatedly do. Excellence, then, is not an act, but a habit.",
  "The secret of your future is hidden in your daily routine.",
  "Motivation gets you started. Habit keeps you going.",
  "Every champion was once a beginner who refused to give up.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "Excellence is not a destination; it is a continuous journey that never ends.",
  "Your habits will determine your future.",
  "The only way to do great work is to love what you do.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "The difference between who you are and who you want to be is what you do.",
  "Dreams don't work unless you do.",
  "The future depends on what you do today.",
  "Be stronger than your excuses.",
  "Start where you are. Use what you have. Do what you can.",
  "The only bad workout is the one that didn't happen.",
  "You miss 100% of the shots you don't take.",
  "It does not matter how slowly you go as long as you do not stop.",
  "The way to get started is to quit talking and begin doing.",
  "Don't watch the clock; do what it does. Keep going.",
  "The only person you are destined to become is the person you decide to be.",
];
